# baseURL = 'http://example.org/'
baseURL = "https://nk35jk.github.io/"
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Naoki Kato'
# theme = "gohugo-theme-ananke"
# theme = "hugo-theme-basic"
# theme = "minimal"
theme = "gokarna"
publishDir = "docs"
canonifyurls = true

# --- gokarna ---
enableEmoji = true
# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  # template
  # [[menu.main]]
  #   identifier = ""
  #   name = ""
  #   url = ""
  #   weight = 1
  #   pre = ""
  #   post = ""

  # home
  # [[menu.main]]
  #   identifier = "home"
  #   name = "Home"
  #   url = ""
  #   weight = 1
  #   pre = ""
  #   post = ""

  # # about
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About Me"
  #   url = "/about/"
  #   weight = 1

  # # news
  # [[menu.main]]
  #   # Unique identifier for a menu item
  #   identifier = "news"
  #
  #   url = "/news/"
  #
  #   # You can add extra information before the name (HTML format is supported), such as icons
  #   pre = ""
  #
  #   # You can add extra information after the name (HTML format is supported), such as icons
  #   post = ""
  #
  #   # Display name
  #   name = "News"
  #
  #   # Weights are used to determine the ordering
  #   weight = 1

  # # blog
  # [[menu.main]]
  #   identifier = "blog"
  #   name = "Blog"
  #   url = "/blog/"
  #   weight = 2
  #
  # # tags
  # [[menu.main]]
  #   identifier = "tags"
  #   name = "Tags"
  #   url = "/tags/"
  #   weight = 3

  # # twitter
  # [[menu.main]]
  #   identifier = "twitter"
  #   # name = "Twitter"
  #   url = "https://twitter.com/nk35jk"
  #   weight = 4
  #   # pre = ""
  #   pre = "<span data-feather='twitter'></span>"
  #   post = ""
  #
  # # linkedin
  # [[menu.main]]
  #   identifier = "linkedin"
  #   # name = "Linkedin"
  #   url = ""
  #   weight = 5
  #   # pre = ""
  #   pre = "<span data-feather='linkedin'></span>"
  #   post = ""
  #
  # # github
  # [[menu.main]]
  #   identifier = "github"
  #   # name = "Github"
  #   url = "https://github.com/nk35jk"
  #   weight = 6
  #   # We use feather-icons: https://feathericons.com/
  #   pre = "<span data-feather='github'></span>"
  #
  # # speakerdeck
  # [[menu.main]]
  #   identifier = "speakerdeck"
  #   name = "Speaker Deck"
  #   url = "https://speakerdeck.com/nk35jk"
  #   weight = 7
  #   pre = "<span data-feather='sd'></span>"
  #   post = ""
  #
  # # kaggle
  # [[menu.main]]
  #   identifier = "kaggle"
  #   name = "Kaggle"
  #   url = "https://www.kaggle.com/nk35jk"
  #   weight = 8
  #   # pre = ""
  #   pre = "<span data-feather='kaggle'></span>"
  #   post = ""

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  # description = "Computer Vision Researcher / Engineer"
  description = "PhD Student | Freelance Engineer"
  # subdescription = "I'm interested in deep learning, especially learning from unlabeled data."
  subdescription = "Mainly working on computer vision"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#EF4D4D"
  # accentColor = "#000000"
  # accentColor = "#08F"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "research", "computer vision", "deep learning",
                  "machine learning", "neural network", "transformer"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  # showPostsOnHomePage = ""
  # showPostsOnHomePage = "recent"

  # Footer text
  # footer = "The Marauders"

  [[params.socialicons]]
  name = "twitter"
  url = "https://twitter.com/nk35jk"

  [[params.socialicons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/naoki-kato-cv/"

  [[params.socialicons]]
  name = "github"
  url = "https://github.com/nk35jk"

  # [[params.socialicons]]
  # name = "kaggle"
  # url = "https://www.kaggle.com/nk35jk"

  [[params.socialicons]]
  name = "email"
  url = "mailto:naoki.kato.c@gmail.com"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
# ---------------
